import {
  Shield, Database, HardDrive, Cpu, Network, GitMerge, Layers, FileCode,
  FileText, Clock, Users, Lock, Leaf, Zap,
  Globe2, Eye, Scale, Coins,
  Code2, Code, Compass, Monitor, MonitorSmartphone, Globe, Terminal, Boxes,
  Gem, Gauge, AtSign, Fingerprint, Bot, Github, Heart,
  BookOpen, GraduationCap, Package, Server, Wrench,
  MessageCircle, Twitter, Youtube, Newspaper, HelpCircle,
  LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  "shield": Shield,
  "database": Database,
  "hard-drive": HardDrive,
  "cpu": Cpu,
  "network": Network,
  "git-merge": GitMerge,
  "layers": Layers,
  "file-code": FileCode,
  "file-text": FileText,
  "clock": Clock,
  "users": Users,
  "lock": Lock,
  "leaf": Leaf,
  "zap": Zap,
  "globe-2": Globe2,
  "eye": Eye,
  "scale": Scale,
  "coins": Coins,
  "code-2": Code2,
  "code": Code,
  "compass": Compass,
  "monitor": Monitor,
  "monitor-smartphone": MonitorSmartphone,
  "globe": Globe,
  "terminal": Terminal,
  "boxes": Boxes,
  "gem": Gem,
  "gauge": Gauge,
  "at-sign": AtSign,
  "fingerprint": Fingerprint,
  "bot": Bot,
  "github": Github,
  "heart": Heart,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  "package": Package,
  "server": Server,
  "message-circle": MessageCircle,
  "twitter": Twitter,
  "youtube": Youtube,
  "newspaper": Newspaper,
  "help-circle": HelpCircle,
  "wrench": Wrench,
};

export function getIcon(key: string): LucideIcon {
  return iconMap[key] ?? Shield;
}
